#ifndef __ISP_IOMMU_H__
#define __ISP_IOMMU_H__

enum vdev_buffer_layout {
VDEV_BUFFER_LAYOUT_PA_CONTIG    = 0,
VDEV_BUFFER_LAYOUT_VA_CONTIG,
};

#define V4L2_CID_VDEV_BUFFER_LAYOUT           (V4L2_CID_CAMERA_CLASS_BASE + 0x1002)
#define V4L2_CID_VDEV_BUFFER_DETAIN_NUM  (V4L2_CID_CAMERA_CLASS_BASE + 0x1003)
#define V4L2_CID_VDEV_ENABLE_NO_ZOOM       (V4L2_CID_CAMERA_CLASS_BASE + 0x1004)

#endif //__ISP_IOMMU_H__

